Updated main README and supported_examples with MMQA details
mhbuehler/GenAIExamples pull request #13
Opened 2024-11-05 19:10 UTC by okhleif-IL

## Description

Added more information about MultimodalQnA use case in `README.md` and `supported_examples.md`

## Issues

N/A

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

N/A

## Tests

N/A

2024-11-05 19:16 UTC, dmsuehir requested changes

2024-11-05 19:16 UTC, dmsuehir commented on supported_examples.md
> +[MultimodalQnA](./MultimodalQnA/README.md) addresses your questions by dynamically fetching the most pertinent multimodal information (frames, transcripts, and/or captions) from your collection of vi
```suggestion
[MultimodalQnA](./MultimodalQnA/README.md) addresses your questions by dynamically fetching the most pertinent multimodal information (frames, transcripts, and/or captions) from your collection of videos, images, or audio files. MultimodalQnA utilizes BridgeTower model, a multimodal encoding transformer model which merges visual and textual data into a unified semantic space. During the video ingestion phase, the BridgeTower model embeds both visual cues and auditory facts as texts, and those embeddings are then stored in a vector database. When it comes to answering a question, the MultimodalQnA will fetch its most relevant multimodal content from the vector store and feed it into a downstream Large Vision-Language Model (LVM) as input context to generate a response for the user.
```

2024-11-05 19:16 UTC, dmsuehir commented on supported_examples.md
> +| LVM       | [llava-hf/llava-1.5-7b-hf](https://huggingface.co/llava-hf/llava-1.5-7b-hf)        | Xeon/Gaudi | LVM service              |
Gaudi doesn't support llava 1.5 because it's using TGI-gaudi, which only supports 1.6

2024-11-05 19:16 UTC, dmsuehir commented on supported_examples.md
> +| Embedding | [BridgeTower/bridgetower-large-itm-mlm-itc](https://huggingface.co/BridgeTower/bridgetower-large-itm-mlm-itc) | Xeon/Gaudi | Video embeddings service |
Maybe "Video embedding service" ➡️  "Multimodal embedding service"?

2024-11-05 19:16 UTC, dmsuehir commented on supported_examples.md
> +| LVM       | [llava-hf/llava-v1.6-vicuna-13b-hf](https://huggingface.co/llava-hf/llava-v1.6-vicuna-13b-hf)        | Xeon/Gaudi | LVM service              |
I haven't successfully been able to run 1.6 vicuna on Xeon, but this is the default model used for Gaudi

2024-11-05 19:47 UTC, dmsuehir approved these changes
Thanks LGTM

2024-11-06 17:13 UTC, mhbuehler approved these changes
LGTM

2024-11-06 17:30 UTC, merged