Renamed Dataprep Endpoints videos --> files
mhbuehler/GenAIExamples pull request #3
Opened 2024-10-22 23:09 UTC by okhleif-IL

## Description

This PR goes along with [this PR in Comps](https://github.com/mhbuehler/GenAIComps/pull/3). The purpose of this pull request is to rename the dataprep endpoint variables to match the renaming done in the backend.

## Issues

N/A

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

N/A

## Tests

Describe the tests that you ran to verify your changes.

Running the curl commands and checking logs has verified both endpoints are being called successfully under the new names.

2024-10-22 23:43 UTC, mhbuehler approved these changes
LGTM

2024-10-23 20:08 UTC, dmsuehir requested changes

2024-10-23 20:08 UTC, dmsuehir commented on MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
>  ```bash
Could you also update the text around this curl command. For example the line above this says "Also, you are able to get the list of all videos that you uploaded:" (change `videos` ➡️ `files`)

And then below the `curl` command it's also specifically saying `video`.

2024-10-23 20:08 UTC, dmsuehir commented on MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
>  ```bash
Same with this, the markdown is talking about videos specifically.

2024-10-23 20:08 UTC, dmsuehir commented on MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
>  ```bash
Same here

2024-10-23 20:08 UTC, dmsuehir commented on MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
>  ```bash
And here

2024-10-23 20:10 UTC, dmsuehir requested changes
Can you also update:
* MultimodalQnA/tests/test_compose_on_xeon.sh
* MultimodalQnA/tests/test_compose_on_gaudi.sh

These have references to `get_videos` and `delete_videos`

2024-10-23 20:32 UTC, dmsuehir approved these changes
LGTM, thanks

2024-10-23 20:33 UTC, merged